### PR TITLE
Cart

### PR DESCRIPTION
**Pull request by hsuanxuan**

### CODE REVIEW

**Comment by ggjj321** [comment]
Please pay attention to RWD
image

**Comment by hsuanxuan** [comment]
reorganize my homepage.html
partial my page to three part: the top widget, left widget, main widget
expect to use flex to arrange objects

**Comment by hsuanxuan** [comment]
logo
search bar
login
shopping cart 
sidebar (game classification)
main (review image readme  and add button)

**Comment by c1ydehhx** [comment]
The font in homepage.html and homepage2.html is not equal.
Please fix it :D

**Comment by hsuanxuan** [comment]
> The font in homepage.html and homepage2.html is not equal.
> Please fix it :D

That because the css file of the homepage.html are comment out😢
And homepage2.html is the final version!!!

**Pull request merged**
